sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VWou6WDNA/wugxdCwsRnxDge2Nc/uWdcEFejR0jf1Hf0O98IUWsVTRCkWr9NPPDV0cuwBCh58fTT17hptn+jkYT/Zu0v2xpVqwM7+q7WA/Y63ZpMX+I2Mc38BVcAZ05FOxed1q5VhyNuNKBxUevBJ7uOn5BGk+uMSl6Yk1e55YSfs86rrNL7aodU8qJw2iCftjh8CZfTe/u1+bEEUUFKrvHfDxFCxjwjFt8VDLQ/VtZ5w53Va2WATh2c2d8x7QMKyBiuclQ/dCxD+n7RAaB8Kdg9v3dlmG3YUBRIGpENiBpH73f9U3EqPE7HWKrwIgWDPziTovMkyaxtpVmmWack3imgxOcCwDMvHMK0jCx4QpjfIQEV1prvZ37TNGsk9Go0M33hVw6tQuffqOTbmWOj1HPRdHCi8jDjSZ5AlqUHYLBNL7EIgOaCFdXxpeuxIz/6b04tFS0CbdzTdEQtPhBxqQxqc/3Nk5GCOqKMtEcItGa6dAXQZ5tbWiFr24HNzIXYvhY+jhl7rxTaTsa0xOtx21THpwaf71kcXX2QnlU9jf7WRTyEDsHZuP+tvZtmoqACpHtSHKT2fxz1o5uTUcQbOXu58qEACihc8j5obgixoXm/34bhOtwirJCQQrXOOsrmOgOT6imqJYLlK+tVRzX7B7/+xUt/jsoyTbbOg7ptyCM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Woman-s-Way-Through-Unknown-Labrador_4266
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy